### ISSUE TITLE
Isaac's Heart is OP

### ISSUE THREAD

**Issue by ez-duke** [Zamiell/isaac-achievement-randomizer#1]
It should be at least a tier 1 item because it's much more helpful than any other tier 0 item. It drastically increases your dps and it allows you to dodge bosses more easily, because it gives you immunity to creeps, spikes, pits, and you can push the boss and other enemies back.

**Comment by Zamiell** [comment]
I watched anti's stream last night and currently have a wildly different take on Isaac's heart than you do.
If you're in the mood to watch a long VoD, look at this: https://www.twitch.tv/videos/1951040049
He gets Isaac's Heart at the 02:54:00 mark.

**Comment by ez-duke** [comment]
Ok I've watched it. Yeah alright, it still requires a lot of skill to be efficient, it was easier in my head =)
