### ISSUE TITLE
alternative for the boss timed achievment

### ISSUE THREAD

**Issue by pandabbles** [Zamiell/isaac-achievement-randomizer#2]
you could add like timed room or boss fight like instead of making it take no dmg for 1 min you have to clear\kill the boss in under 1 min cuz I feel like most of the time I make the boss one shot and have to wait 30 or 1min just to avoid the boss and if u get hit have fun waiting another 1:30 min

**Comment by Zamiell** [comment]
i dont think having a powerful build and then just simply holding the shoot button down is very skill based

**Comment by pandabbles** [comment]
> i dont think having a powerful build and then just simply holding the shoot button down is very skill 
so make it so it only triggers when you don't have a crazy amount of dmg and tears and with this randomizer i dont think getting a build that just mows down enemies is gonna be easy considering all the broken items are all locked

**Comment by Zamiell** [comment]
i dont want to arbitrarily create a damage threshold for every boss, it is a design goal to make the achievements as non-arbitrary as possible

**Comment by pandabbles** [comment]
I meant it more as a damage threshold for every chapters

**Comment by Zamiell** [comment]
that's less arbitrary but still arbitrary, since bosses of a chapter have heterogeneous difficulty levels
